### ISSUE TITLE
Other baselines methods

### ISSUE THREAD

**Issue by meszlili96** [meszlili96/NaturalComputing#3]

**Comment by EvgeniyaMartynova** [comment]
Add two (?) SOTA GANs implementation to compare with our method. Look for those designed to issues E-GAN is designed to tackle: mode collapse and training instability (if not too complex).

**Comment by meszlili96** [comment]
1. Really good post about problems with training GANs and possible solutions: [From GAN to WGAN](https://lilianweng.github.io/lil-log/2017/08/20/from-GAN-to-WGAN.html). Papers mentioned:
* Improved Techniques for Training GANs: [code](https://github.com/openai/improved-gan), [article](https://papers.nips.cc/paper/6125-improved-techniques-for-training-gans.pdf),
* Wasserstein GAN: [code](https://github.com/martinarjovsky/WassersteinGAN), [article](https://arxiv.org/pdf/1701.07875.pdf) (easy).
2. Energy-based GAN to improve training stability: [code](https://github.com/buriburisuri/ebgan), [article](https://arxiv.org/pdf/1609.03126.pdf) (complex).
3. Spectral normalization for generative adversarial networks: [code](https://github.com/pfnet-research/sngan_projection), [article](https://arxiv.org/pdf/1802.05957.pdf) (easy).
